apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-service
  template:
    metadata:
      labels:
        app: example-service
    spec:
      containers:
        - name: example-service
          image: ubuntu:latest
          ports:
            - containerPort: 8080 
          env:
            - name: DD_API_KEY
              value: your-datadog-api-key
          # Add any other environment variables your application needs here
      # Add any other Kubernetes-specific configurations you need here
